#!/usr/bin/env python3
"""Converts a BMP into a C++ source file with its pixels as an RGB565 array,
so the image can be built into the firmware instead of read from the SD card.

Usage:
    scripts/bmp_to_rgb565.py resources/buttons.bmp src/buttons_image.cpp kButtonsImage

The generated file defines
    extern const std::uint16_t <name>[];      // width*height pixels, top row first
    extern const std::uint16_t <name>Width, <name>Height;
Re-run it whenever the BMP changes. Needs Pillow (pip install pillow).
"""
import sys
from PIL import Image

def main():
    if len(sys.argv) != 4:
        print(__doc__)
        sys.exit(1)
    src, dst, name = sys.argv[1:4]
    im = Image.open(src).convert("RGB")
    w, h = im.size
    px = im.load()
    words = []
    for y in range(h):
        for x in range(w):
            r, g, b = px[x, y]
            # Same conversion as bmp_loader.hpp
            words.append(((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3))
    with open(dst, "w") as f:
        f.write("// Generated by scripts/bmp_to_rgb565.py from %s -- do not edit.\n" % src)
        f.write("// %d x %d pixels, RGB565, top row first.\n" % (w, h))
        f.write("#include <cstdint>\n\n")
        f.write("extern const std::uint16_t %sWidth = %d;\n" % (name, w))
        f.write("extern const std::uint16_t %sHeight = %d;\n" % (name, h))
        f.write("extern const std::uint16_t %s[%d] = {\n" % (name, w * h))
        for i in range(0, len(words), 12):
            f.write("    " + ", ".join("0x%04X" % v for v in words[i:i + 12]) + ",\n")
        f.write("};\n")
    print("%s: %dx%d -> %s (%s)" % (src, w, h, dst, name))

if __name__ == "__main__":
    main()
